import shutil

import pytest

from revision_engine.diagrams import graphviz_version, render_dot, stamp_anchors
from revision_engine.errors import BuildError

needs_dot = pytest.mark.skipif(shutil.which("dot") is None, reason="graphviz dot not installed")

DOT = 'digraph g { rankdir=LR; node [shape=box]; a [label="main()" id="main-fn"]; b [label="add" id="add-fn"]; a -> b; }\n'


@needs_dot
def test_renders_inline_svg_fragment(tmp_path):
    p = tmp_path / "flow.dot"
    p.write_text(DOT, encoding="utf-8")
    svg = render_dot(p, "L/diagrams/flow.dot")
    assert svg.startswith("<svg") and svg.rstrip().endswith("</svg>")
    assert "<?xml" not in svg and "<!DOCTYPE" not in svg and "Generated by graphviz" not in svg
    assert 'class="rv-svg' in svg
    assert 'data-node="main-fn"' in svg and 'data-node="add-fn"' in svg


@needs_dot
def test_syntax_error_is_build_error(tmp_path):
    p = tmp_path / "bad.dot"
    p.write_text("digraph { a -> ; }", encoding="utf-8")
    with pytest.raises(BuildError, match=r"L/bad\.dot: graphviz failed"):
        render_dot(p, "L/bad.dot")


def test_stamp_anchors_marks_matching_nodes():
    svg = (
        '<svg><g id="main-fn" class="node" data-node="main-fn"><title>a</title></g>'
        '<g id="x" class="node" data-node="x"></g></svg>'
    )
    out = stamp_anchors(svg, {"main-fn"})
    assert 'data-anchor="main-fn"' in out and "rv-svg-anchor" in out
    assert 'data-anchor="x"' not in out


def test_graphviz_version_is_string_or_none():
    v = graphviz_version()
    assert v is None or isinstance(v, str)
